In [1]:
import numpy as np

In [2]:
A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
B = np.random.rand(5,5)
A@B

array([[0.94198411, 0.57480634, 0.76061737, 0.26906557, 0.61304571],
       [0.21320407, 0.24039814, 0.87497718, 0.13819018, 0.49472847],
       [0.88099934, 0.01650302, 0.12793705, 0.65204277, 0.29786899],
       [0.78937603, 0.8917995 , 0.54528565, 0.09624445, 0.5009495 ],
       [0.71474162, 0.44963326, 0.95029437, 0.9953691 , 0.77825962]])

In [4]:
W = np.random.rand(16,16) - 0.5
B = np.random.rand(16)

W@B

array([ 1.3891732 , -1.93006152, -0.39129485,  0.52591148, -0.09115689,
       -0.67054252,  0.09173577,  0.20187764,  0.8347829 , -0.27032279,
        0.90169208,  0.02661907, -1.94118485,  0.10589677,  0.41280273,
        0.90827995])