In [2]:
import numpy as np

In [3]:
A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
B = np.random.rand(5,5)
A@B

array([[0.18471184, 0.85378853, 0.97079404, 0.00212277, 0.99013938],
       [0.67041262, 0.23624295, 0.0273834 , 0.99999585, 0.02858432],
       [0.67232475, 0.20546484, 0.96288227, 0.70143732, 0.08259626],
       [0.93725262, 0.49136938, 0.48679691, 0.76829937, 0.03246676],
       [0.90601552, 0.52394656, 0.43101757, 0.32128565, 0.71134144]])

In [5]:
W = np.random.rand(16,16) - 0.5
B = np.random.rand(16)

W@B

array([ 0.66918438,  0.52906297, -0.31039842,  0.72832089, -0.55968792,
        0.59110061, -0.74971617, -0.28508288,  0.57317967, -0.01270507,
        0.40956235, -0.52049878,  0.21771006,  1.26442341,  0.83453223,
        1.0627281 ])